# Generated by Django 3.0 on 2019-12-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_number', models.IntegerField(default='', verbose_name='研究编号')),
                ('study_name', models.CharField(default='', max_length=50, verbose_name='研究名称')),
                ('study_disease', models.CharField(default='', max_length=20, verbose_name='研究疾病')),
                ('study_medicine', models.CharField(default='', max_length=25, verbose_name='研究药物/器械')),
                ('responsible_person', models.CharField(default='', max_length=10, verbose_name='负责人')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('article', models.CharField(default='', max_length=20, verbose_name='文章发表情况')),
                ('influence', models.CharField(default='', max_length=20, verbose_name='影响因子')),
                ('funds', models.CharField(default='', max_length=30, verbose_name='经费来源')),
                ('pay', models.CharField(default='', max_length=100, verbose_name='费用')),
                ('util', models.CharField(default='', max_length=5, verbose_name='单位')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
    ]
