# Generated by Django 3.0 on 2019-12-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'UserMessage'},
        ),
    ]
