# Generated by Django 3.0 on 2020-01-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='userpassword',
        ),
    ]
