# Generated by Django 3.0 on 2019-12-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0003_auto_20191204_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
    ]
