# Generated by Django 3.0 on 2019-12-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbmysql',
            name='dbcls_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbinfo.dbmysqlcls', verbose_name='外键，父表dbmysqlcls'),
        ),
    ]
