# Generated by Django 3.0 on 2019-12-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0006_auto_20191204_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbmysqlcls',
            old_name='idcvip',
            new_name='idcoip',
        ),
    ]
