# Generated by Django 3.0 on 2019-12-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0007_auto_20191204_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbmongodb',
            old_name='dbidc_id',
            new_name='dbidc',
        ),
        migrations.RenameField(
            model_name='dbmysql',
            old_name='dbcls_id',
            new_name='dbcls',
        ),
        migrations.RenameField(
            model_name='dbmysql',
            old_name='dbidc_id',
            new_name='dbidc',
        ),
        migrations.RenameField(
            model_name='dbredis',
            old_name='dbidc_id',
            new_name='dbidc',
        ),
    ]
