# Generated by Django 3.0 on 2019-12-05 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0008_auto_20191204_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbmongodbcls',
            old_name='idcvip',
            new_name='idcoip',
        ),
    ]
