# Generated by Django 2.2.3 on 2019-08-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='alex', max_length=32),
            preserve_default=False,
        ),
    ]
