# Generated by Django 3.0 on 2019-12-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20191218_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='content',
            field=models.TextField(),
        ),
    ]
