# Generated by Django 3.0 on 2019-12-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_userprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
