# Generated by Django 3.0 on 2019-12-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list', '可以访问表的数据列表页'),)},
        ),
    ]
