# Generated by Django 3.0 on 2019-12-24 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='content',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='host_to_remote_user',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='web.HostToRemoteUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='log_type',
            field=models.SmallIntegerField(choices=[(0, 'login'), (1, 'cmd'), (2, 'logout')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='堡垒机账号'),
            preserve_default=False,
        ),
    ]
