# Generated by Django 3.0 on 2019-12-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_task_tasklogdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklogdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'initialized'), (1, 'success'), (2, 'failed'), (3, 'timeout')], default=0),
        ),
    ]
