# Generated by Django 3.0 on 2019-12-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_tasklogdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='任务内容'),
        ),
    ]
